# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Playwright Staging

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  FORESIGHT_UPLOADER_SIGNER_URL: https://upload.service.runforesight.us/
  WORKFLOW_TELEMETRY_BASE_URL: https://api.service.runforesight.us
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        with:
          api_key: ${{ secrets.FRS_STAGING_TOKEN }}
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test
        env:
          # This might depend on your test-runner/language binding
          PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
      - name: Foresight test kit
        if: success() || failure()
        uses: runforesight/foresight-test-kit-action@v1
        with:
          api_key: ${{ secrets.FRS_STAGING_TOKEN }}
          test_format: JUNIT
          test_framework: JEST
          test_path: ./results.xml   
