# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        with:
          api_key: ${{ secrets.FRS_PROD_API_KEY }}
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: |
          npm install
          npx playwright install
          npx nyc next dev &
      - name: Run Playwright tests
        run: npx playwright test
      - name: Kill server
        run: |
          kill -9 $(lsof -t -i:3000)
      - name: Foresight test kit
        if: success() || failure()
        uses: thundra-io/foresight-test-kit-action@v1
        with:
          api_key: ${{ secrets.FRS_PROD_API_KEY }}
          test_format: JUNIT
          test_framework: JEST
          test_path: ./results.xml
          coverage_format: COBERTURA/XML
          coverage_path: coverage/*.xml
