# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        with:
          api_key: ${{ secrets.FRS_PROD_API_KEY }}
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: |
          npm ci
          npm install
          npx playwright install chromium --with-deps
          npx nyc next dev &
        env:
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
      - name: Run Playwright tests
        run: npx playwright test
        env:
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
      - name: Kill server
        if: always()
        run: |
          lsof -t -i:3000
          kill -9 $(lsof -t -i:3000)
      - name: Foresight test kit
        if: success() || failure()
        uses: thundra-io/foresight-test-kit-action@v1
        with:
          api_key: ${{ secrets.FRS_PROD_API_KEY }}
          test_format: JUNIT
          test_framework: JEST
          test_path: ./results.xml
          coverage_format: COBERTURA/XML
          coverage_path: coverage/*.xml
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: ./coverage
